config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'pages#home'

  # error pages
  %w( 403 404 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '/events/:event_id/locations', controller: :event_locations,
                                     action: :index, defaults: { format: :json }

  scope :countries, controller: :countries do
    get "/", action: :index
    get "/:country/subdivisions", action: :subdivisions
  end

  devise_for :admins, path: :game_control,
                      controllers: { sessions: 'game_control/sessions',
                                     invitations: 'game_control/invitations' }

  namespace :game_control do
    root 'dashboard#index', as: 'root'

    get 'profile.json', to: 'profile#show'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    patch 'profile/password', to: 'profile#update_password'

    resources 'cities'
    resources 'admins'
    resources 'events', except: :edit do
      resources 'event_locations' do
        get 'copy'
      end
    end
    resources 'pages'
  end

  get '*path', to: 'pages#show', as: :page,
    constraints: { path: /(?!game_control).*/ }
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :invitable, :database_authenticatable, :lockable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

  rolify
  include Authority::UserAbilities
  include Authority::Abilities

  attr_accessor :send_invite

  has_and_belongs_to_many :cities, optonal: true

  validates :email, :full_name, :roles, presence: true

  def avatar
    "https://robohash.org/#{email}.png?set=set3&bgset=bg2"
  end
end

app/controllers/game_control/admins_controller.rb
class GameControl::AdminsController < GameControlController
  authorize_actions_for Admin

  add_breadcrumb "<i class='fa fa-users'></i> Users".html_safe, :game_control_admins_path

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
    @admin.send_invite = true
    @cities = cities
  end

  def create
    @admin = Admin.new(create_params)
    @admin.password = temp_password

    if @admin.save
      @admin.invite! if create_params[:send_invite] == '1'
      redirect_to game_control_admins_path, notice: 'User successfully created.'
    else
      @cities = cities
      render :new
    end
  end

  def edit
    @admin = Admin.find params[:id]
    @cities = cities
  end

  def update
    @admin = Admin.find params[:id]

    if @admin.update_attributes(update_params)
      redirect_to game_control_admins_path,
                  notice: "User <strong>#{@admin.full_name}</strong> was successfully updated"
    else
      @cities = cities
      render :edit
    end
  end

  def destroy
    admin = Admin.find params[:id]
    admin.destroy
    redirect_to game_control_admins_path, notice: 'User successfully deleted.'
  end

  private

  def temp_password
    Devise.friendly_token
  end

  def cities
    City.all.sort { |x, y| x.full_display_name <=> y.full_display_name }
  end

  def create_params
    params[:admin].delete_if { |k, v| k == 'password' && v.empty? }
    params.required(:admin).permit(:full_name, :email, :send_invite,
                                   role_ids: [], city_ids: [])
  end

  def update_params
    params[:admin].delete_if { |k, v| k == 'password' && v.empty? }
    params.required(:admin).permit(:full_name, :email, :password,
                                   role_ids: [], city_ids: [])
  end
end

app/controllers/game_control/cities_controller.rb
class GameControl::CitiesController < GameControlController
  authorize_actions_for City

  add_breadcrumb "<i class='fa fa-building'></i> Cities".html_safe, :game_control_cities_path

  def index
    @cities = City.parent_cities.order(:name)
  end

  def new
    @city = City.new
    generate_parents
    @states = []
  end

  def create
    @city = City.new(city_params)

    if @city.save
      redirect_to :game_control_cities, notice: 'City successfully created.'
    else
      generate_parents
      render :new
    end
  end

  def edit
    @city = City.find params[:id]
    generate_states
    generate_parents
  end

  def update
    @city = City.find params[:id]

    if @city.update_attributes(city_params)
      redirect_to :game_control_cities,
                  notice: "City <strong>#{@city.full_display_name}</strong> was successfully updated"
    else
      generate_states
      generate_parents
      render :edit
    end
  end

  def destroy
    city = City.find params[:id]
    city.destroy
    redirect_to :game_control_cities, notice: 'city successfully deleted.'
  end

  private

  def generate_states
    @states = Country.new.states(@city.country).map do |s|
      OpenStruct.new(s)
    end
  end

  def generate_parents
    @parents = City.parent_cities.order(:name)
  end

  def city_params
    params.require(:city).permit(:name, :display_name, :state, :country, :parent_id)
  end
end

app/controllers/game_control/dashboard_controller.rb
class GameControl::DashboardController < GameControlController
  def index
    @upcoming_event = Event.upcoming
    @locations = @upcoming_event&.event_locations&.select do |l|
      current_admin.cities.map(&:id).include?(l.city_id)
    end
  end
end

app/controllers/game_control/event_locations_controller.rb
class GameControl::EventLocationsController < GameControlController
  authorize_actions_for EventLocation, except: [:edit, :update, :copy]

  before_action :load_event, :add_breadcrumbs

  def new
    @location = @event.event_locations.build
    @cities = available_cities
    @states = []
  end

  def create
    @location = EventLocation.new(create_params)
    if @location.save
      redirect_to game_control_event_path(@event),
                  notice: 'Location successfully created.'
    else
      @cities = available_cities
      render :new
    end
  end

  def copy
    event = Event.find params[:event_id]
    @location = (EventLocation.find params[:event_location_id]).dup
    @location.event = event
    # Delete any existing location record for this month/event
    event.event_locations.where(city: @location.city).destroy_all
    if @location.save
      redirect_to game_control_event_path(@event),
                  notice: 'Location successfully created.'
    else
      @cities = available_cities
      render :new
    end
  end

  def edit
    @location = EventLocation.find params[:id]
    @recent_locations = @location.city.recent_locations(@location.event.event_at, 3)
    authorize_action_for(@location)
    generate_states
  end

  def update
    @location = EventLocation.find params[:id]
    authorize_action_for(@location)

    if @location.update_attributes(update_params)
      redirect_to game_control_event_path(@event),
                  notice: "Location was successfully updated"
    else
      generate_states
      render :edit
    end
  end

  def destroy
    location = EventLocation.find params[:id]
    location.destroy
    redirect_to game_control_event_path(@event),
                notice: 'Location successfully deleted.'
  end

  private

  def generate_states
    @states = Country.new.states(@location.addr_country).map do |s|
      OpenStruct.new(s)
    end
  end

  def available_cities
    all_cities = City.all.sort { |x, y| x.full_display_name <=> y.full_display_name }
    event_cities = @event.event_locations.map(&:city)
    all_cities - event_cities
  end

  def load_event
    @event = Event.find(params[:event_id])
  end

  def create_params
    params.require(:event_location).permit(:city_id, :event_id, :bar_name,
                                           :bar_url, :start_time, :notes,
                                           :addr_street_1, :addr_street_2, :addr_postal_code,
                                           :addr_city, :addr_state, :addr_country)
  end

  def update_params
    params.require(:event_location).permit(:bar_name, :bar_url, :start_time, :notes,
                                           :addr_street_1, :addr_street_2, :addr_postal_code,
                                           :addr_city, :addr_state, :addr_country)
  end

  def add_breadcrumbs
    add_breadcrumb "<i class='fa fa-calendar'></i> Events".html_safe, :game_control_events_path
    add_breadcrumb @event.theme, game_control_event_path(@event)
  end
end

app/controllers/game_control/events_controller.rb
class GameControl::EventsController < GameControlController
  authorize_actions_for Event

  add_breadcrumb "<i class='fa fa-calendar'></i> Events".html_safe, :game_control_events_path

  def index
    @events = Event.all.order(event_at: :desc)
  end

  def new
    @event = Event.new
    @cities = City.parent_cities.order(:name)
    @event.puzzle_set = params[:puzzle_set_id]
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      EventService.new.add_event_locations(@event, params[:city_ids])
      redirect_to game_control_event_path(@event), notice: 'Event successfully created.'
    else
      @cities = City.parent_cities.order(:name)
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    load_location_data
  end

  def update
    @event = Event.find params[:id]

    if @event.update_attributes(event_params)
      redirect_to game_control_event_path(@event),
                  notice: "Event was successfully updated"
    else
      load_location_data
      render :show
    end
  end

  def destroy
    event = Event.find params[:id]
    event.destroy
    redirect_to game_control_events_path, notice: 'Event successfully deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:event_at, :theme)
  end

  def load_location_data
    @locations = build_locations
    @admin_locations = @locations.select do |l|
      current_admin.cities.map(&:id).include?(l.city_id)
    end
  end

  def build_locations
    @event.event_locations.sort { |x, y| x.city.display_name <=> y.city.display_name }
  end
end

app/controllers/game_control/hints_controller.rb
class GameControl::HintsController < ApplicationController
    authorize_actions_for Hint
    before_action :set_game_control_hint, only: [:show, :edit, :update, :destroy]
    before_action :set_game_control_puzzle_set_and_puzzle
    add_breadcrumb "<i class='fa fa-question-sign'></i> Hint".html_safe, :game_control_hint_path

  # GET /game_control/hints
  # GET /game_control/hints.json
  def index
    @game_control_hints = Hint.all
  end

  # GET /game_control/hints/1
  # GET /game_control/hints/1.json
  def show
  end

  # GET /game_control/hints/new
  def new
    @game_control_hint = Hint.new
  end

  # GET /game_control/hints/1/edit
  def edit
  end

  # POST /game_control/hints
  # POST /game_control/hints.json
  def create
    @game_control_hint = Hint.new(game_control_hint_params)

    respond_to do |format|
      if @game_control_hint.save
        format.html { redirect_to @game_control_hint, notice: 'Hint was successfully created.' }
        format.json { render :show, status: :created, location: @game_control_hint }
      else
        format.html { render :new }
        format.json { render json: @game_control_hint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_control/hints/1
  # PATCH/PUT /game_control/hints/1.json
  def update
    respond_to do |format|
      if @game_control_hint.update(game_control_hint_params)
        format.html { redirect_to @game_control_hint, notice: 'Hint was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_control_hint }
      else
        format.html { render :edit }
        format.json { render json: @game_control_hint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_control/hints/1
  # DELETE /game_control/hints/1.json
  def destroy
    @game_control_hint.destroy
    respond_to do |format|
      format.html { redirect_to game_control_hints_url, notice: 'Hint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_game_control_puzzle_set_and_puzzle
      @puzzle_set = PuzzleSet.find(params[:puzzle_set_id])
      @puzzle = PuzzleSet.find(params[:puzzle_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_game_control_hint
      @game_control_hint = Hint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_control_hint_params
      params.require(:game_control_hint).permit(:title)
    end
end

app/controllers/game_control/invitations_controller.rb
class GameControl::InvitationsController < Devise::InvitationsController
  def after_accept_path_for(_)
    game_control_root_path
  end
end

app/controllers/game_control/pages_controller.rb
class GameControl::PagesController < GameControlController
  authorize_actions_for Page

  add_breadcrumb "<i class='fa fa-files-o'></i> Pages".html_safe, :game_control_pages_path

  def index
    @pages = Page.where(parent: nil).order(:full_path)
  end

  def new
    @page = Page.new
    new_parents
  end

  def create
    @page = Page.new(parameters)
    if @page.save
      redirect_to edit_game_control_page_path(@page),
                  notice: 'Page successfully created.'
    else
      new_parents
      render :new
    end
  end

  def edit
    @page = Page.find params[:id]
    update_parents
  end

  def update
    @page = Page.find params[:id]

    if @page.update_attributes(parameters)
      redirect_to edit_game_control_page_path(@page),
                  notice: 'Page successfully updated.'
    else
      update_parents
      render :edit
    end
  end

  def destroy
    page = Page.find params[:id]
    page.destroy
    redirect_to game_control_pages_path, notice: 'Page successfully deleted.'
  end

  private

  def new_parents
    @parents = Page.order(:full_path)
  end

  def update_parents
    @parents = Page.where.not(id: @page.id).order(:full_path)
  end

  def parameters
    params.require(:page).
      permit(:active, :title, :slug, :content, :parent_id)
  end
end

app/controllers/game_control/profile_controller.rb
class GameControl::ProfileController < GameControlController
  skip_before_action :authenticate_admin!, only: :show
  before_action -> { doorkeeper_authorize! :login }, only: :show

  def show
    admin = Admin.find(doorkeeper_token.resource_owner_id)
    scopes = doorkeeper_token.scopes

    profile = Profile.new(admin, scopes)

    render json: profile
  end

  def edit
    @admin = current_admin
  end

  def update
    @admin = current_admin
    if @admin.update(update_params)
      sign_in @admin, bypass_sign_in: true
      redirect_to game_control_profile_path,
                  notice: 'Your profile as been update successfully'
    else
      render :edit
    end
  end

  def update_password
    @admin = current_admin
    if @admin.update_with_password(password_params)
      sign_in @admin, bypass_sign_in: true
      redirect_to game_control_profile_path,
                  notice: 'Your password as been update successfully'
    else
      render :edit
    end
  end

  private

  def update_params
    params.required(:admin).permit(:full_name, :email)
  end

  def password_params
    params.required(:admin).permit(:password, :password_confirmation,
                                   :current_password)
  end
end

app/controllers/game_control/puzzles_controller.rb
class GameControl::PuzzlesController < GameControlController
    authorize_actions_for Puzzle
    before_action :set_game_control_puzzle, only: [:show, :edit, :update, :destroy]
    before_action :set_game_control_puzzle_set
    add_breadcrumb "<i class='fa fa-puzzle'></i> Puzzle".html_safe, :game_control_puzzle_path

  # GET /game_control/puzzles
  # GET /game_control/puzzles.json
  def index
    @puzzles = Puzzle.all
  end

  # GET /game_control/puzzles/1
  # GET /game_control/puzzles/1.json
  def show
  end

  # GET /game_control/puzzles/new
  def new
    @puzzle = Puzzle.new
  end

  # GET /game_control/puzzles/1/edit
  def edit
  end

  # POST /game_control/puzzles
  # POST /game_control/puzzles.json
  def create
    @puzzle = Puzzle.new(game_control_puzzle_params)

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render :show, status: :created, location: @puzzle }
      else
        format.html { render :new }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_control/puzzles/1
  # PATCH/PUT /game_control/puzzles/1.json
  def update
    respond_to do |format|
      if @puzzle.update(game_control_puzzle_params)
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzle }
      else
        format.html { render :edit }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_control/puzzles/1
  # DELETE /game_control/puzzles/1.json
  def destroy
    @puzzle.destroy
    respond_to do |format|
      format.html { redirect_to game_control_puzzles_url, notice: 'Puzzle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_control_puzzle_set
      @puzzle_set = PuzzleSet.find(params[:puzzle_set_id])
    end

    def set_game_control_puzzle
      @puzzle = Puzzle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_control_puzzle_params
      params.require(:puzzle).permit(:title)
    end
end

app/helpers/game_control/dashboard_helper.rb
module GameControl::DashboardHelper
end

app/views/game_control/events/_locations_table.html.slim
.table-responsive
  table.js-location_table.table.table-bordered.table-hover
    thead
      tr
        th Location
        th Bar
        th.hidden-xs Notes
        th.col-sm-1
    tbody
      - locations.each do |location|
        tr
          td
            strong = location.city.full_display_name
          td
            address
              - if location.bar_name.present?
                = location.bar_name
                br
              - if location.addr_street_1.present?
                = location.addr_street_1
                br
              - if location.addr_street_2.present?
                = location.addr_street_2
                br
              - state = display_state(location.addr_country, location.addr_state)
              = [location.addr_city, state].compact.reject(&:empty?).join(',')
              =< location.addr_postal_code
              br
              = location.addr_country
              br
              strong Start Time
              =< location.start_time.to_s(:time)
          td.hidden-xs
            dl
              = location.notes.html_safe if location.notes
          td.text-right
            -if current_admin.can_manage?(location)
              .btn-group
                button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  span.caret
                ul class="dropdown-menu dropdown-menu-right"
                  - if current_admin.can_update?(location)
                    li
                      = link_to edit_game_control_event_event_location_path(event, location)
                        span.text-nowrap
                          i.fa.fa-pencil
                          span< edit
                  - if current_admin.can_delete?(location)
                    li
                      = link_to game_control_event_event_location_path(event, location, :authenticity_token => form_authenticity_token()),
                        method: :delete, data: { confirm: 'Are you sure?'}
                        span.text-nowrap
                          i.fa.fa-trash
                          span< delete
            - elsif current_admin.can_update?(location)
              = link_to edit_game_control_event_event_location_path(event, location)
                span.text-nowrap
                  i.fa.fa-pencil
                  span< edit

app/views/game_control/events/index.html.slim
- content_for :page_header, 'Manage Events'
- content_for :page_description, 'update event info'

.row
  .col-sm-12
    .box.box-primary
      .box-header.with-border
        .box-title
          i.fa.fa-calendar>
          |  Events
        - if current_admin.can_create?(Event)
          .box-tools.pull-left
            = link_to :new_game_control_event, class: 'btn btn-sm btn-default'
              i.fa.fa-user-plus>
              | Add New Event

      .box-body
        .table-responsive
          table#event_table.table.table-bordered.table-hover.table-striped.table-condensed
            thead
              tr
                th Event Date
                th Theme
                th.col-sm-1
            tbody
              - @events.each do |event|
                tr
                  td = event.event_at
                  td = event.theme
                  td.text-right
                    - if current_admin.can_manage?(event)
                      .btn-group
                        button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                          span.caret
                        ul class="dropdown-menu dropdown-menu-right"
                          - if current_admin.can_manage?(event)
                            li
                              = link_to game_control_event_path(event)
                                span.text-nowrap
                                  i.fa.fa-pencil<
                                  span<> view&nbsp;/&nbsp;edit
                            - unless event.past?
                              li
                                = link_to game_control_event_path(event, :authenticity_token => form_authenticity_token()),
                                  method: :delete, data: { confirm: 'Are you sure?'}
                                  span.text-nowrap
                                    i.fa.fa-trash<
                                    span< delete
                    - elsif current_admin.can_read?(event)
                      = link_to game_control_event_path(event)
                        span.text-nowrap
                          i.fa.fa-eye<
                          span< view

javascript:
  $(document).ready(function() {
    $('#event_table').DataTable({
      "order": [[ 0, "desc" ]],
      "columns": [{"orderable": true},
                  {"orderable": false},
                  {"orderable": false}
                 ]
    });
  });

app/views/game_control/events/new.html.slim
- content_for :page_header, "New Event"
- content_for :page_description, 'create a new Event'
- add_breadcrumb 'New', new_game_control_event_path

= simple_form_for @event, url: game_control_events_path do |f|
  .row
    .col-sm-12
      .box.box-primary
        .box-header.with-border
          .box-title
            i.fa.fa-calendar>
            | Event Info for
            = @event.theme
          .box-body
            = f.input :event_at

  .row
    .col-sm-12
      .box.box-primary
        .box-header.with-border
          .box-title
            i.fa.fa-building>
            | Cities
          .box-body
            ul
              - @cities.each do |city|
                li
                  => check_box_tag 'city_ids[]', city.id, city.children.empty?, id: "city-#{city.id}"
                  =< label_tag "city-#{city.id}", city.display_name
                  - city.children.each do |child|
                    ul
                      li
                        => check_box_tag 'city_ids[]', child.id, true, id: "city-#{child.id}"
                        =< label_tag "city-#{child.id}", child.display_name
          .box-footer
            .pull-right
              =<> link_to 'Cancel', game_control_cities_path,
                html_options = { class: 'btn btn-default' }
              =<> f.submit 'Save', class: 'btn btn-primary'

app/views/game_control/events/show.html.slim
- content_for :page_header, @event.theme
- content_for :page_description, 'update event details'
- add_breadcrumb @event.theme, game_control_event_path(@event)

.row
  .col-sm-12
    .box.box-primary
      .box-header.with-border
        .box-title
          i.fa.fa-calendar>
          |  Event Info
        - if current_admin.can_manage?(@event)
          = simple_form_for [:game_control, @event]  do |f|
            .box-body
              .form-group.string.required
                = f.label :event_at
                .input-group.date
                  .input-group-addon
                    i.fa.fa-calendar
                  = f.input :event_at, as: :string, label: false,
                    input_html: { class: 'js-datepicker' }
              = f.input :theme
            .box-footer
              .pull-right
                =<> link_to 'Cancel', game_control_events_path,
                  html_options = { class: 'btn btn-default' }
                =<> f.submit 'Save', class: 'btn btn-primary'
        - else
          .box-body
              dl
                dt Event Date
                dd = @event.event_at
                dt Theme
                dd = @event.theme

- if current_admin.can_manage?(@event) && !@naughty.empty?
  .row
    .col-sm-12
      .box.box-primary
        .box-header.with-border
          .box-title
            i.fa.fa-calendar>
            |  Naughty List — Cities Missing Locations
          <div style="margin-top:20px; columns:150px 4;">
            ul
              - for item in @naughty
                li 
                  a href="#{@event.id}/event_locations/#{item.id}/edit" #{item.city.full_display_name}
                  / Fix these when we get a hiatus/canceled flag. This string stuff is inefficient.
                  - if nil != item.notes.to_s.downcase.index("hiatus")
                    |  (on hiatus)
                  - elsif nil != item.notes.to_s.downcase.index("canceled") || nil != item.notes.to_s.downcase.index("cancelled")
                    |  (canceled)
          </div>

.row
  .col-sm-12
    .box.box-primary
      .box-header.with-border
        .box-title
          i.fa.fa-building>
          = "Your Location".pluralize(@admin_locations.count)
      .box-body
        .row
          .col-sm-12
            = render partial: "locations_table", locals: {event: @event, locations: @admin_locations}

.row
  .col-sm-12
    .box.box-primary
      .box-header.with-border
        .box-title
          i.fa.fa-building>
          | All Locations
        .box-tools.pull-left
          = link_to new_game_control_event_event_location_path(@event),
            class: 'btn btn-sm btn-default'
            span.text-nowrap
              i.fa.fa-plus>
              | Add New Location
      .box-body
        .row
          .col-sm-12
            = render partial: "locations_table", locals: {event: @event, locations: @locations}

- content_for :js_footer
  javascript:
    $(document).ready(function() {
      $('.js-datepicker').datepicker({
        autoclose: true,
        format: 'dd M yyyy',
        disableTouchKeyboard: true,
        toggleActive: false
      });

      $('.js-location_table').DataTable({
        "order": [[ 0, "asc" ]],
        "columns": [{"orderable": true},
                    {"orderable": true},
                    {"orderable": false},
                    {"orderable": false}
                   ]
      });
    });