config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'pages#home'

  # error pages
  %w( 403 404 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get '/events/:event_id/locations', controller: :event_locations,
                                     action: :index, defaults: { format: :json }

  scope :countries, controller: :countries do
    get "/", action: :index
    get "/:country/subdivisions", action: :subdivisions
  end

  devise_for :admins, path: :game_control,
                      controllers: { sessions: 'game_control/sessions',
                                     invitations: 'game_control/invitations' }

  namespace :game_control do
    root 'dashboard#index', as: 'root'

    get 'profile.json', to: 'profile#show'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    patch 'profile/password', to: 'profile#update_password'

    resources 'cities'
    resources 'admins'
    resources 'events', except: :edit do
      resources 'event_locations' do
        get 'copy'
      end
    end
    resources 'pages'
  end

  get '*path', to: 'pages#show', as: :page,
    constraints: { path: /(?!game_control).*/ }
end

app/views/layouts/_devise_header.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    title Puzzled Pint - Game Control
    / Tell the browser to be responsive to screen width
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"
    / Font Awesome --
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css"
    / Ionicons --
    link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    = stylesheet_link_tag "game_control"
    = javascript_include_tag 'game_control', 'data-turbolinks-track' => true

    /!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /!-- WARNING: Respond.js doesn't work if you view the page via file://
    /!--[if lt IE 9]
    script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"
    /![endif]

    = javascript_include_tag 'analytics'

app/views/layouts/_game_control_sidebar.html.slim
/! Left side column. contains the logo and sidebar
aside.main-sidebar
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! Sidebar Menu
    ul.sidebar-menu
      li#dashboard
        = link_to :game_control_root
          i.fa.fa-dashboard
          span Dashboard

      // Event Management
      // ===============
      - if current_admin.can_read?(Event)
        li#events.treeview
          a href="#"
            i.fa.fa-calendar
            span Events
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li#events-index
              = link_to :game_control_events
                i.fa.fa-list
                span List
            - if current_admin.can_create?(Event)
              li#events-new
                = link_to :new_game_control_event
                  i.fa.fa-plus
                  span Add


      // City Management
      // ===============
      - if current_admin.can_manage?(City)
        li#cities.treeview
          a href="#"
            i.fa.fa-building
            span Cities
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li#cities-index
              = link_to :game_control_cities
                i.fa.fa-list
                span List
            li#cities-new
              = link_to :new_game_control_city
                i.fa.fa-plus
                span Add

      // Page Management
      // ===============
      - if current_admin.can_manage?(Page)
        li#pages.treeview
          a href="#"
            i.fa.fa-files-o
            span Pages
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li#pages-index
              = link_to :game_control_pages
                i.fa.fa-list
                span List
            li#files-new
              = link_to :new_game_control_page
                i.fa.fa-plus
                span Add

      // User Management
      // ===============
      - if current_admin.can_manage?(Admin)
        li#admins.treeview
          a href="#"
            i.fa.fa-users
            span Users
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li#admins-index
              = link_to :game_control_admins
                i.fa.fa-list
                span List
            li#admins-new
              = link_to :new_game_control_admin
                i.fa.fa-plus
                span Add

      // Puzzle Set Management
      // ===============
      - if current_admin.can_manage?(PuzzleSet)
        li#puzzleSets.treeview
          a href="#"
            i.fa.fa-list
            span Puzzle Sets
            i.fa.fa-angle-left.pull-right
          ul.treeview-menu
            li#puzzle-sets-index
              = link_to :game_control_puzzle_sets
                i.fa.fa-list
                span List
            - if current_admin.can_create?(PuzzleSet)
              li#puzzle-sets-new
                = link_to :new_game_control_puzzle_set
                  i.fa.fa-plus
                  span Add
    /! /.sidebar-menu
  /! /.sidebar
/! /.main-sidebar

javascript:
  gamecontrol.sidebar.init('#{controller_name}', '#{action_name}');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    title Puzzled Pint
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    #wrapper
      #header
       #logo
          h1
            a href="/"
              span Puzzled Pint
       #navigation
          ul.nav-header
            li.nav-selected.nav-path-selected.first
              a.nav-selected.nav-path-selected.first href="/"
                | home
            li
              a href="/about/" about
            li
              a href="/puzzles/" puzzles
            li
              a href="/standings/" standings
            li
              a href="/faq/" faq
            li
              a href="/resources/" resources
            li
              a href="http://blog.puzzledpint.com/" blog
      .clear:both

      #content
        == yield

      #footer
        #license_info
          | Unless otherwise noted, content on this site is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.

app/views/layouts/devise.html.slim
= render "/layouts/devise_header"
body.hold-transition.yellow-blue.sidebar-mini class="#{content_for :body_class}"
  == yield
  = javascript_include_tag 'game_control_footer.js'

javascript:
  analytics.page()
- if current_admin
  javascript:
    analytics.identify('#{current_admin.id}', {
      name: '#{current_admin.full_name}',
      email: '#{current_admin.email}',
      roles: #{current_admin.roles.map(&:name).to_json.html_safe}
      }
    );

app/views/layouts/devise_login.html.slim
- content_for :
= render "/layouts/devise_header"
.login-box
  .login-logo
    = link_to :game_control_root
      b PuzzledPint
      | GC
  /! /.login-logo
  .login-box-body
    - if alert
      p.login-box-msg.text-red = alert
    - if notice
      p.login-box-msg.text-yellow = noitce

    == yield
  /! /.login-box-body

javascript:
  analytics.page()

app/views/layouts/game_control.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    title Puzzled Pint - Game Control
    / Tell the browser to be responsive to screen width
    meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'
    / Font Awesome --
    link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'
    / Ionicons --
    link rel='stylesheet' href='https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'

    = stylesheet_link_tag 'game_control', 'data-turbolinks-track' => true
    = javascript_include_tag 'game_control', 'data-turbolinks-track' => true
    = javascript_include_tag 'analytics'
    = yield(:js_header).presence

    /!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /!-- WARNING: Respond.js doesn't work if you view the page via file://
    /!--[if lt IE 9]
    script src='https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js'
    script src='https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js'
    /![endif]


  / BODY TAG OPTIONS:
    =================
   Apply one or more of the following classes to get the
   desired effect
   |---------------------------------------------------------|
   | SKINS         | skin-blue                               |
   |               | skin-black                              |
   |               | skin-purple                             |
   |               | skin-yellow                             |
   |               | skin-red                                |
   |               | skin-green                              |
   |---------------------------------------------------------|
   |LAYOUT OPTIONS | fixed                                   |
   |               | layout-boxed                            |
   |               | layout-top-nav                          |
   |               | sidebar-collapse                        |
   |               | sidebar-mini                            |
   |---------------------------------------------------------|

  body.hold-transition.skin-yellow.sidebar-mini
    .wrapper
      / -- Main Header -->
      header.main-header
        /! Logo
        = link_to :game_control_root, class: :logo
          /! mini logo for sidebar mini 50x50 pixels
          span.logo-mini
            b PP
            |GC
          /! logo for regular state and mobile devices
          span.logo-lg
            b PuzzledPint
            |GC
        /! Header Navbar
        nav.navbar.navbar-static-top role='navigation' 
          /! Sidebar toggle button
          a.sidebar-toggle data-toggle='offcanvas' href='#' role='button' 
            span.sr-only Toggle navigation
          /! Navbar Right Menu
          .navbar-custom-menu
            ul.nav.navbar-nav
              /! User Account Menu
              li.dropdown.user.user-menu
                /! Menu Toggle Button
                a.dropdown-toggle data-toggle='dropdown' href='#' 
                  /! The user image in the navbar
                  = image_tag current_admin.avatar, class: 'user-image', alt: 'User _Image'
                  /! hidden-xs hides the username on small devices so only the image appears.
                  span.hidden-xs< = current_admin.full_name
                ul.dropdown-menu
                  /! The user image in the menu
                  li.user-header
                    = image_tag current_admin.avatar, class: 'img-circle', alt: 'User _Image'
                    p
                      = current_admin.full_name
                      small Member since #{current_admin.created_at.strftime('%B %Y')}
                  li.user-footer
                    .pull-left
                      = link_to 'Profile', game_control_profile_path, class: "btn btn-default btn-flat"
                    .pull-right
                      = link_to 'Sign Out',
                        destroy_admin_session_path(:authenticity_token => form_authenticity_token()),
                        method: :delete, class: 'btn btn-default btn-flat'
      = render 'layouts/game_control_sidebar'
      /! Content Wrapper. Contains page content
      .content-wrapper
        /! Content Header (Page header)
        section.content-header
          - if content_for? :page_header
            h1
              == yield :page_header
              -if content_for? :page_description
                small == yield :page_description
          ol.breadcrumb
            = render_breadcrumbs tag: :li, separator: ''
        /! Main content
        section.content
          /! Alert flash
          - if alert
            .alert.alert-danger.alert-dismissible
              button type='button' class='close' data-dismiss='alert' aria-hidden='true' &times;
              h4
                i class='icon fa fa-ban'
                | Alert
              = alert.html_safe
          /! /.alert-danger
          /! Info flash
          - if notice
            .alert.alert-info.alert-dismissible
              button type='button' class='close' data-dismiss='alert' aria-hidden='true' &times;
              h4
                i class='icon fa fa-info'
                | Info
              = notice.html_safe
          /! /.alert-info
          == yield
        /! /.content
      /! /.content-wrapper
      /! Main Footer
      footer.main-footer
        /! To the right
        .pull-right.hidden-xs
        /! Default to the left
        strong
      / ./wrapper
      / REQUIRED JS SCRIPTS
      = javascript_include_tag 'game_control_footer.js'
      = yield(:js_footer).presence

javascript:
  analytics.page()
- if current_admin
  javascript:
    analytics.identify('#{current_admin.id}', {
      name: '#{current_admin.full_name}',
      email: '#{current_admin.email}',
      roles: #{current_admin.roles.map(&:name).to_json.html_safe}
      }
    );

app/views/layouts/home.html.slim
doctype html
html
  head
    meta charset='utf-8'
    title Puzzled Pint
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    #wrapper
      #content
        == yield